import type { ThemePreset } from "@/types/theme";

/**
 * Built-in QR code presets
 */
export const defaultPresets: Record<string, ThemePreset> = {
  classic: {
    label: "Classic",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#000000",
      eyeColor: "#000000",
      dotColor: "#000000",
      bodyPattern: "circle",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  modern: {
    label: "Modern",
    styles: {
      bgColor: "#f8fafc",
      fgColor: "#0f172a",
      eyeColor: "#3b82f6",
      dotColor: "#3b82f6",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  vibrant: {
    label: "Vibrant",
    styles: {
      bgColor: "#fef3c7",
      fgColor: {
        type: "radial",
        stops: [
          { color: "#dc2626", offset: 0 },
          { color: "#7c2d12", offset: 100 },
        ],
      },
      eyeColor: "#dc2626",
      dotColor: "#ea580c",
      bodyPattern: "diamond",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "diamond",
      level: "Q",
    },
  },
  minimal: {
    label: "Minimal",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#404040",
      eyeColor: "#404040",
      dotColor: "#404040",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  gradientBlue: {
    label: "Ocean Blue",
    styles: {
      bgColor: "#eff6ff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#1e40af", offset: 0 },
          { color: "#3b82f6", offset: 100 },
        ],
        angle: 135,
      },
      eyeColor: "#3b82f6",
      dotColor: "#60a5fa",
      bodyPattern: "circle-large",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  neon: {
    label: "Neon",
    styles: {
      bgColor: "#0f172a",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#22d3ee", offset: 0 },
          { color: "#a855f7", offset: 50 },
          { color: "#ec4899", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: "#a855f7",
      dotColor: "#ec4899",
      bodyPattern: "circle-mixed",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  nature: {
    label: "Nature",
    styles: {
      bgColor: "#f0fdf4",
      fgColor: "#166534",
      eyeColor: "#15803d",
      dotColor: "#16a34a",
      bodyPattern: "rounded",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  retro: {
    label: "Retro",
    styles: {
      bgColor: "#fef2f2",
      fgColor: "#7f1d1d",
      eyeColor: "#b91c1c",
      dotColor: "#dc2626",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  amberMinimal: {
    label: "Amber Minimal",
    styles: {
      bgColor: "#fffbeb",
      fgColor: "#92400e",
      eyeColor: "#f59e0b",
      dotColor: "#fbbf24",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  amethystHaze: {
    label: "Amethyst Haze",
    styles: {
      bgColor: "#faf5ff",
      fgColor: "#6b21a8",
      eyeColor: "#a855f7",
      dotColor: "#c084fc",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  boldTech: {
    label: "Bold Tech",
    styles: {
      bgColor: "#f3e8ff",
      fgColor: "#581c87",
      eyeColor: "#7c3aed",
      dotColor: "#3b82f6",
      bodyPattern: "diamond",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "diamond",
      level: "Q",
    },
  },
  bubblegum: {
    label: "Bubblegum",
    styles: {
      bgColor: "#fdf2f8",
      fgColor: "#9f1239",
      eyeColor: "#ec4899",
      dotColor: "#fbbf24",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  caffeine: {
    label: "Caffeine",
    styles: {
      bgColor: "#fef3c7",
      fgColor: "#78350f",
      eyeColor: "#92400e",
      dotColor: "#a16207",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  candyland: {
    label: "Candyland",
    styles: {
      bgColor: "#fef9c3",
      fgColor: "#854d0e",
      eyeColor: "#eab308",
      dotColor: "#3b82f6",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  emerald: {
    label: "Emerald",
    styles: {
      bgColor: "#ecfdf5",
      fgColor: "#064e3b",
      eyeColor: "#10b981",
      dotColor: "#34d399",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  rose: {
    label: "Rose",
    styles: {
      bgColor: "#fff1f2",
      fgColor: "#881337",
      eyeColor: "#e11d48",
      dotColor: "#f43f5e",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  slate: {
    label: "Slate",
    styles: {
      bgColor: "#f8fafc",
      fgColor: "#0f172a",
      eyeColor: "#475569",
      dotColor: "#64748b",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  sunset: {
    label: "Sunset",
    styles: {
      bgColor: "#fff7ed",
      fgColor: "#9a3412",
      eyeColor: "#ea580c",
      dotColor: "#f97316",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  midnight: {
    label: "Midnight",
    styles: {
      bgColor: "#0f172a",
      fgColor: "#e0e7ff",
      eyeColor: "#6366f1",
      dotColor: "#818cf8",
      bodyPattern: "circle",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  // New presets with gradients and variety
  gradientSunset: {
    label: "Gradient Sunset",
    styles: {
      bgColor: "#fff7ed",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#f97316", offset: 0 },
          { color: "#dc2626", offset: 100 },
        ],
        angle: 135,
      },
      eyeColor: "#ea580c",
      dotColor: "#f97316",
      bodyPattern: "rounded",
      cornerEyePattern: "extra-rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  gradientOcean: {
    label: "Gradient Ocean",
    styles: {
      bgColor: "#f0f9ff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#0ea5e9", offset: 0 },
          { color: "#3b82f6", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: {
        type: "radial",
        stops: [
          { color: "#3b82f6", offset: 0 },
          { color: "#1e40af", offset: 100 },
        ],
      },
      dotColor: "#60a5fa",
      bodyPattern: "circle-large",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  gradientPurple: {
    label: "Gradient Purple",
    styles: {
      bgColor: "#faf5ff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#a855f7", offset: 0 },
          { color: "#7c3aed", offset: 100 },
        ],
        angle: 90,
      },
      eyeColor: "#9333ea",
      dotColor: {
        type: "radial",
        stops: [
          { color: "#c084fc", offset: 0 },
          { color: "#a855f7", offset: 100 },
        ],
      },
      bodyPattern: "diamond",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  gradientForest: {
    label: "Gradient Forest",
    styles: {
      bgColor: "#f0fdf4",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#16a34a", offset: 0 },
          { color: "#15803d", offset: 100 },
        ],
        angle: 180,
      },
      eyeColor: "#22c55e",
      dotColor: "#4ade80",
      bodyPattern: "circle-mixed",
      cornerEyePattern: "diya",
      cornerEyeDotPattern: "diya",
      level: "Q",
    },
  },
  cyberpunk: {
    label: "Cyberpunk",
    styles: {
      bgColor: "#030712",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#ec4899", offset: 0 },
          { color: "#8b5cf6", offset: 50 },
          { color: "#06b6d4", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: "#a855f7",
      dotColor: "#ec4899",
      bodyPattern: "pacman",
      cornerEyePattern: "pointy",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  pastelDream: {
    label: "Pastel Dream",
    styles: {
      bgColor: "#fefce8",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#fbbf24", offset: 0 },
          { color: "#f472b6", offset: 50 },
          { color: "#a78bfa", offset: 100 },
        ],
        angle: 120,
      },
      eyeColor: "#c084fc",
      dotColor: "#f472b6",
      bodyPattern: "rounded",
      cornerEyePattern: "extra-rounded",
      cornerEyeDotPattern: "rounded-triangle",
      level: "Q",
    },
  },
  monochrome: {
    label: "Monochrome",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#1f2937",
      eyeColor: "#4b5563",
      dotColor: "#6b7280",
      bodyPattern: "small-square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  tropical: {
    label: "Tropical",
    styles: {
      bgColor: "#f0fdfa",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#14b8a6", offset: 0 },
          { color: "#0d9488", offset: 100 },
        ],
        angle: 135,
      },
      eyeColor: "#2dd4bf",
      dotColor: "#5eead4",
      bodyPattern: "circle",
      cornerEyePattern: "curly",
      cornerEyeDotPattern: "banner",
      level: "Q",
    },
  },
  royal: {
    label: "Royal",
    styles: {
      bgColor: "#fef3c7",
      fgColor: {
        type: "radial",
        stops: [
          { color: "#92400e", offset: 0 },
          { color: "#78350f", offset: 100 },
        ],
      },
      eyeColor: "#d97706",
      dotColor: "#f59e0b",
      bodyPattern: "diamond",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  lavender: {
    label: "Lavender",
    styles: {
      bgColor: "#faf5ff",
      fgColor: "#6b21a8",
      eyeColor: "#a855f7",
      dotColor: "#c084fc",
      bodyPattern: "circle-large",
      cornerEyePattern: "extra-rounded",
      cornerEyeDotPattern: "rounded-triangle",
      level: "Q",
    },
  },
  fire: {
    label: "Fire",
    styles: {
      bgColor: "#1c1917",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#f97316", offset: 0 },
          { color: "#dc2626", offset: 50 },
          { color: "#991b1b", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: "#ea580c",
      dotColor: "#f97316",
      bodyPattern: "circle-mixed",
      cornerEyePattern: "pointy",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  ice: {
    label: "Ice",
    styles: {
      bgColor: "#f0f9ff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#0ea5e9", offset: 0 },
          { color: "#0284c7", offset: 100 },
        ],
        angle: 90,
      },
      eyeColor: "#38bdf8",
      dotColor: "#7dd3fc",
      bodyPattern: "rounded",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  message: {
    label: "Message",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#1e40af",
      eyeColor: "#3b82f6",
      dotColor: "#60a5fa",
      bodyPattern: "square",
      cornerEyePattern: "message",
      cornerEyeDotPattern: "message",
      level: "Q",
    },
  },
  diya: {
    label: "Diya",
    styles: {
      bgColor: "#fff7ed",
      fgColor: {
        type: "radial",
        stops: [
          { color: "#f97316", offset: 0 },
          { color: "#c2410c", offset: 100 },
        ],
      },
      eyeColor: "#ea580c",
      dotColor: "#fb923c",
      bodyPattern: "circle",
      cornerEyePattern: "diya",
      cornerEyeDotPattern: "diya-reverse",
      level: "Q",
    },
  },
  starry: {
    label: "Starry Night",
    styles: {
      bgColor: "#0f172a",
      fgColor: {
        type: "radial",
        stops: [
          { color: "#e0e7ff", offset: 0 },
          { color: "#6366f1", offset: 100 },
        ],
      },
      eyeColor: "#818cf8",
      dotColor: "#a5b4fc",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  banner: {
    label: "Banner",
    styles: {
      bgColor: "#f8fafc",
      fgColor: "#475569",
      eyeColor: "#64748b",
      dotColor: "#94a3b8",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "banner",
      level: "Q",
    },
  },
  pointy: {
    label: "Pointy",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#7c2d12",
      eyeColor: "#991b1b",
      dotColor: "#dc2626",
      bodyPattern: "diamond",
      cornerEyePattern: "pointy",
      cornerEyeDotPattern: "rounded-triangle",
      level: "Q",
    },
  },
  curly: {
    label: "Curly",
    styles: {
      bgColor: "#fdf2f8",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#ec4899", offset: 0 },
          { color: "#be185d", offset: 100 },
        ],
        angle: 135,
      },
      eyeColor: "#f472b6",
      dotColor: "#f9a8d4",
      bodyPattern: "rounded",
      cornerEyePattern: "curly",
      cornerEyeDotPattern: "rounded-triangle",
      level: "Q",
    },
  },
  pacman: {
    label: "Pacman",
    styles: {
      bgColor: "#1e293b",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#fbbf24", offset: 0 },
          { color: "#f59e0b", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: "#fbbf24",
      dotColor: "#fcd34d",
      bodyPattern: "pacman",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  rainbow: {
    label: "Rainbow",
    styles: {
      bgColor: "#ffffff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#ef4444", offset: 0 },
          { color: "#f97316", offset: 16.66 },
          { color: "#eab308", offset: 33.33 },
          { color: "#22c55e", offset: 50 },
          { color: "#3b82f6", offset: 66.66 },
          { color: "#8b5cf6", offset: 83.33 },
          { color: "#ec4899", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: {
        type: "radial",
        stops: [
          { color: "#3b82f6", offset: 0 },
          { color: "#8b5cf6", offset: 100 },
        ],
      },
      dotColor: {
        type: "radial",
        stops: [
          { color: "#ec4899", offset: 0 },
          { color: "#f97316", offset: 100 },
        ],
      },
      bodyPattern: "circle-mixed",
      cornerEyePattern: "extra-rounded",
      cornerEyeDotPattern: "star",
      level: "Q",
    },
  },
  spiderman: {
    label: "Spiderman",
    styles: {
      bgColor: "#000000",
      fgColor: "#ffffff",
      eyeColor: "#ff0000",
      dotColor: "#ff0000",
      bodyPattern: "diamond",
      cornerEyePattern: "diya",
      cornerEyeDotPattern: "diya",
      level: "Q",
    },
  },
  twitter: {
    label: "Twitter",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#000000",
      eyeColor: "#1DA1F2",
      dotColor: "#000000",
      bodyPattern: "square",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
  instagram: {
    label: "Instagram",
    styles: {
      bgColor: "#ffffff",
      fgColor: {
        type: "linear",
        stops: [
          { color: "#833AB4", offset: 0 },
          { color: "#E1306C", offset: 50 },
          { color: "#FCAF45", offset: 100 },
        ],
        angle: 45,
      },
      eyeColor: {
        type: "radial",
        stops: [
          { color: "#E1306C", offset: 0 },
          { color: "#833AB4", offset: 100 },
        ],
      },
      dotColor: {
        type: "radial",
        stops: [
          { color: "#FCAF45", offset: 0 },
          { color: "#E1306C", offset: 100 },
        ],
      },
      bodyPattern: "circle",
      cornerEyePattern: "extra-rounded",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  netflix: {
    label: "Netflix",
    styles: {
      bgColor: "#000000",
      fgColor: "#E50914",
      eyeColor: "#E50914",
      dotColor: "#E50914",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "Q",
    },
  },
} as const;
